base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
  os:
    name: ubi
    namespace: ocp
    tag: "8"
releases:
  initial:
    candidate:
      product: ocp
      stream: nightly
      version: "4.13"
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.13"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: mtr-interop-aws-macharya
  cron: 0 1 * * 1
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: aws.interop.ccitredhat.com
      SPOT_INSTANCES: "true"
    workflow: ipi-aws
zz_generated_metadata:
  branch: main
  org: rhpit
  repo: interop-tests
  variant: macharya-ocp4.13-lp-interop
